# Generated by Django 2.1.3 on 2019-11-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='contract_success_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_rate',
            field=models.FloatField(default=0),
        ),
    ]
