# Generated by Django 2.1.3 on 2019-11-28 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_category', multiselectfield.db.fields.MultiSelectField(choices=[(1, '원룸'), (2, '투룸'), (3, '쓰리룸'), (4, '포룸'), (5, '쉐어하우스'), (11, '오피스텔'), (21, '아파트'), (22, '빌라'), (23, '단독주택'), (24, '상가주택'), (31, '상가'), (41, '토지')], max_length=30)),
                ('area', models.IntegerField(default=0)),
                ('to_area', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('trade_category', multiselectfield.db.fields.MultiSelectField(choices=[(1, '매매'), (2, '전세'), (3, '월세'), (4, '교환')], max_length=7)),
                ('buying_price', models.BigIntegerField(default=0)),
                ('deposit', models.BigIntegerField(default=0)),
                ('monthly_fee', models.IntegerField(default=0)),
                ('end_date', models.DateTimeField()),
                ('moving_date', models.DateField()),
                ('additional_request', models.CharField(blank=True, max_length=45)),
                ('etc', models.TextField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.Question'),
        ),
    ]
