# Generated by Django 2.1.3 on 2019-11-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20191129_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='area',
        ),
        migrations.RemoveField(
            model_name='question',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='question',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='question',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='location',
        ),
        migrations.RemoveField(
            model_name='question',
            name='monthly_fee',
        ),
        migrations.RemoveField(
            model_name='question',
            name='to_area',
        ),
        migrations.RemoveField(
            model_name='question',
            name='trade_category',
        ),
    ]
