# Generated by Django 2.1.3 on 2019-12-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20191203_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='area',
            new_name='from_area',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='location',
            new_name='from_location',
        ),
        migrations.AddField(
            model_name='question',
            name='to_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
