# Generated by Django 2.1.3 on 2019-11-29 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20191129_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='buying_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='deposit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='question',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='monthly_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='moving_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='question',
            name='to_area',
            field=models.IntegerField(default=0),
        ),
    ]
