# Generated by Django 2.1.3 on 2019-11-29 07:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20191129_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='trade_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '매매'), (2, '전세'), (3, '월세'), (4, '교환')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='moving_date',
            field=models.DateField(),
        ),
    ]
