# Generated by Django 2.1.3 on 2019-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20191210_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateField(),
        ),
    ]
