# Generated by Django 2.1.3 on 2019-12-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_answer_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='accoeted_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answer', to='questions.Question'),
        ),
    ]
