# Generated by Django 2.1.3 on 2019-12-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_answer_accoeted_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='accoeted_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
