# Generated by Django 2.1.3 on 2019-12-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20191219_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_accpeted',
            field=models.BooleanField(default=False),
        ),
    ]
