# Generated by Django 2.1.3 on 2019-12-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_question_answer_accpeted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_accpeted',
            new_name='is_answer_accepted',
        ),
    ]
