# Generated by Django 2.1.3 on 2019-12-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20191219_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='accept',
            new_name='is_accepted',
        ),
    ]
