# Generated by Django 2.1.3 on 2019-12-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20191219_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_answer_accepted',
            new_name='is_question_done',
        ),
    ]
