# Generated by Django 2.1.3 on 2019-12-24 14:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20191223_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pros_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '중개사'), (2, '세무사'), (3, '법무사'), (4, '변호사'), (4, '대출'), (12, '가전구매'), (13, '가구구매'), (14, '인테리어'), (15, '청소'), (16, '이사')], default=0, max_length=24),
        ),
    ]
