# Generated by Django 2.1.3 on 2019-12-26 00:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_question_pros_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='buying_price',
            new_name='trade_price',
        ),
        migrations.AlterField(
            model_name='question',
            name='item_category',
            field=models.IntegerField(choices=[(1, '원룸'), (2, '투룸'), (3, '쓰리룸'), (4, '포룸'), (5, '쉐어하우스'), (6, '오피스텔'), (21, '아파트'), (22, '빌라'), (23, '단독주택'), (24, '상가주택'), (31, '상가'), (41, '토지')], default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='pros_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '중개사'), (2, '세무사'), (3, '법무사'), (4, '변호사'), (11, '대출'), (12, '인테리어'), (13, '청소'), (14, '이사'), (21, '가전구매'), (22, '가구구매')], default=0, max_length=25),
        ),
    ]
