# Generated by Django 2.1.3 on 2019-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20191230_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='item_category',
            field=models.CharField(choices=[('ONR', '원룸'), ('TWR', '투룸'), ('THR', '쓰리룸'), ('FOR', '포룸'), ('SHH', '쉐어하우스'), ('OFT', '오피스텔'), ('APT', '아파트'), ('VIL', '빌라'), ('HOS', '단독주택'), ('CMH', '상가주택'), ('STO', '상가'), ('LND', '토지')], default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='trade_category',
            field=models.CharField(choices=[('TR', '매매'), ('DL', '전세'), ('RT', '월세'), ('EX', '교환'), ('CS', '상담')], default=0, max_length=2),
        ),
    ]
