# Generated by Django 2.1.3 on 2019-12-30 12:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20191230_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='item_category',
            field=models.CharField(choices=[('ONR', '원룸'), ('TWR', '투룸'), ('THR', '쓰리룸'), ('FOR', '포룸'), ('SHH', '쉐어하우스'), ('OFT', '오피스텔'), ('APT', '아파트'), ('VIL', '빌라'), ('HOS', '단독주택'), ('CMH', '상가주택'), ('STO', '상가'), ('LND', '토지')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='pros_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('REB', '중개'), ('TAX', '세무'), ('RGS', '등기'), ('LAW', '법률'), ('LON', '대출'), ('INR', '인테리어'), ('CLN', '청소'), ('MOV', '이사'), ('PRC', '입주사전점검'), ('HAP', '가전구매'), ('FRP', '가구구매')], default='NA', max_length=43),
        ),
        migrations.AlterField(
            model_name='question',
            name='trade_category',
            field=models.CharField(choices=[('TR', '매매'), ('DL', '전세'), ('RT', '월세'), ('EX', '교환'), ('CS', '상담')], default='NA', max_length=2),
        ),
    ]
