# Generated by Django 2.1.3 on 2019-12-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20191230_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='trade_category',
            new_name='transaction_category',
        ),
    ]
