# Generated by Django 2.1.3 on 2019-12-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20191230_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='from_area',
            new_name='from_building_area',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='to_area',
            new_name='from_land_area',
        ),
        migrations.RemoveField(
            model_name='question',
            name='additional_request',
        ),
        migrations.AddField(
            model_name='question',
            name='to_building_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='to_land_area',
            field=models.IntegerField(default=0),
        ),
    ]
