# Generated by Django 2.1.3 on 2019-12-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20191231_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='from_building_area',
            new_name='building_area',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='from_land_area',
            new_name='land_area',
        ),
        migrations.RemoveField(
            model_name='question',
            name='to_building_area',
        ),
        migrations.RemoveField(
            model_name='question',
            name='to_land_area',
        ),
    ]
