# Generated by Django 2.1.3 on 2020-02-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_auto_20191231_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='moving_date',
            new_name='move_date',
        ),
    ]
